resources:
- role.yaml
- role_binding.yaml
- deployment.yaml
- service.yaml
- api_service.yaml


apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: ghcr.io/kedacore/keda-metrics-apiserver
  newName: docker.io/rlanhellas/keda-metrics-apiserver
  newTag: main
