default_stages: [pre-commit, pre-push]
minimum_pre_commit_version: "4.0.0"
exclude: (^vendor/|^pkg/generated/)
repos:
  - repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.5.1
    hooks:
      - id: go-fmt
        name: Run go fmt against the code
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: detect-private-key
        exclude: pkg/scalers/prometheus_scaler_test.go
      - id: end-of-file-fixer
      - id: check-merge-conflict
      - id: mixed-line-ending
  - repo: https://github.com/thlorenz/doctoc.git
    rev: v2.2.0
    hooks:
      - id: doctoc
        name: Add TOC for md files
        files: ^README\.md$|^CONTRIBUTING\.md$
        args:
          - "--maxlevel"
          - "3"
  - repo: local
    hooks:
      - id: language-matters
        language: pygrep
        name: Check for language that we do not accept as community
        description: Please use "deny_list" or "allow_list"  instead.
        entry: "(?i)(black|white)[_-]?(list|List)"
        pass_filenames: true
      - id: sort-scalers
        name: Check if scalers are sorted in scalers_builder.go
        language: system
        entry: "bash tools/sort_scalers.sh"
        files: .*scalers_builder\.go$
      - id: validate-changelog
        name: Validate Changelog
        language: system
        entry: "bash hack/validate-changelog.sh"
        pass_filenames: false
      - id: golangci-lint
        language: system
        name: Run golangci against the code
        entry: make golangci
        pass_filenames: false
