[[constraint]]
  name = "github.com/Sirupsen/logrus"
  version = "1.3.0"

[[constraint]]
  name = "github.com/kelseyhightower/envconfig"
  version = "1.3.0"

# Kubernetes incubator deps
[[constraint]]
  name = "github.com/kubernetes-incubator/custom-metrics-apiserver"
  revision = "bb8bae16c5550f2aeef3151259a1b36078a0e544" #revision number for 1.12.0 release

[[constraint]]
  name = "k8s.io/api"
  version = "kubernetes-1.12.3"

[[constraint]]
  name = "k8s.io/apimachinery"
 branch = "release-1.12"

[[override]]
  name = "k8s.io/apiserver"
  revision = "9601a7bf41efece7e12a8f9f74d2c3b10cdd998e"

[[constraint]]
  name = "k8s.io/metrics"
  branch = "release-1.12"

[[override]]
  name = "k8s.io/kube-openapi"
  revision = "d8ea2fe547a448256204cfc68dfee7b26c720acb"

[[override]]
  name = "github.com/evanphx/json-patch"
  revision = "afac545df32f2287a079e2dfb7ba2745a643747e"

[[override]]
  name = "github.com/coreos/etcd"
  revision = "33245c6b5b49130ca99280408fadfab01aac0e48"

[[override]]
  name = "github.com/ugorji/go"
  revision = "b4c50a2b199d93b13dc15e78929cfb23bfdf21ab"

[[override]]
  name = "github.com/emicklei/go-restful"
  revision = "e64cccdfee8896c036b8a88d560c5e3ae15d904d"


[[constraint]]
  name = "k8s.io/client-go"
    branch = "release-9.0"

[[constraint]]
  name = "k8s.io/code-generator"
  version = "kubernetes-1.13.3"

[[constraint]]
  branch = "master"
  name = "k8s.io/gengo"

[prune]
  non-go = true
  go-tests = true
  unused-packages = true

  [[prune.project]]
    name = "k8s.io/code-generator"
    unused-packages = false
    non-go = false
    go-tests = false

  [[prune.project]]
    name = "k8s.io/gengo"
    unused-packages = false
    non-go = false
    go-tests = false

[[constraint]]
  branch = "master"
  name = "golang.org/x/tools"

[[constraint]]
  name = "github.com/Azure/azure-storage-queue-go"
  version = "0.2.0"



[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "1.19.27"
