resources:
- manager.yaml
- service.yaml

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: ghcr.io/kedacore/keda
  newName: docker.io/aliaqel736/keda
  newTag: 2.18-aliaqel-test-force-activation
