resources:
- webhooks.yaml
- service.yaml
- validation_webhooks.yaml

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: ghcr.io/kedacore/keda-admission-webhooks
  newName: docker.io/rlanhellas/keda-admission-webhooks
  newTag: main
