version: 2

jobs:
  build:
    docker:
      - image: projectkore.azurecr.io/build-tools:latest
        auth:
            username: $ACR_USERNAME
            password: $ACR_PASSWORD
    working_directory: /go/src/github.com/Azure/Kore
    steps:
      - checkout
      - setup_remote_docker
      - run: docker login -u "${ACR_USERNAME}" -p "${ACR_PASSWORD}" ${ACR_REGISTRY}
      - run: az login --service-principal -u "${AZURE_SP_ID}" -p "${AZURE_SP_KEY}" --tenant "${AZURE_SP_TENANT}"
      - run: make test
      - run: make ci-build-all
      - run: make publish-edge-chart
