{{- if .Values.customResourceDefinition.create -}}
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: scaledobjects.keda.k8s.io
  annotations:
    "helm.sh/hook": crd-install
spec:
  group: keda.k8s.io
  version: v1alpha1
  names:
    kind: ScaledObject
    singular: scaledobject
    plural: scaledobjects
    shortNames:
    - sco
    categories:
    - keda
  scope: Namespaced
  additionalPrinterColumns:
  - name: Deployment
    type: string
    JSONPath: .spec.scaleTargetRef.deploymentName
  - name: Triggers
    type: string
    JSONPath: .spec.triggers[*].type
  - name: Age
    type: date
    JSONPath: .metadata.creationTimestamp
{{- end -}}