{{- if .Values.customResourceDefinition.create -}}
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: triggerauthentications.keda.k8s.io
  annotations:
    "helm.sh/hook": crd-install
spec:
  group: keda.k8s.io
  version: v1alpha1
  names:
    kind: TriggerAuthentication
    singular: triggerauthentication
    plural: triggerauthentications
    shortNames:
    - ta
    categories:
    - keda
  scope: Namespaced
{{- end -}}