apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: keda-operator
    app.kubernetes.io/name: keda-operator
    app.kubernetes.io/version: "1.4.0"
    app.kubernetes.io/component: operator
    app.kubernetes.io/part-of: keda-operator
  name: keda-operator
  namespace: keda
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keda-operator
  template:
    metadata:
      labels:
        app: keda-operator
        name: keda-operator
      name: keda-operator
    spec:
      serviceAccountName: keda-operator
      containers:
        - name: keda-operator
          image: docker.io/kedacore/keda:1.4.0
          command:
          - keda
          args:
          - '--zap-level=info'
          - '--zap-time-encoding=epoch'
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              value: ""
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "keda-operator"
