apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: example-triggerauthentication
spec:
  secretTargetRef:
    - parameter: example-secret-parameter
      name: example-secret-name
      key: example-role-key
