---
- op: add
  path: /spec/template/spec/volumes/-
  value:
    name: auth-volume
    emptyDir: {}
- op: add
  path: /spec/template/spec/initContainers
  value:
    - name: init-auth
      image: busybox
      command: [sh, -c, "echo '{\"authMode\":\"bearer\",\"token\":\"e2e-mock-test-bearer-token\"}' > /mnt/auth/creds.json"]
      volumeMounts:
        - name: auth-volume
          mountPath: /mnt/auth
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
- op: add
  path: /spec/template/spec/containers/0/args/-
  value: --filepath-auth-root-path=/mnt/auth
- op: add
  path: /spec/template/spec/containers/0/volumeMounts/-
  value:
    name: auth-volume
    mountPath: /mnt/auth
    readOnly: true
