# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/keda.sh_scaledobjects.yaml
- bases/keda.sh_scaledjobs.yaml
- bases/keda.sh_triggerauthentications.yaml
- bases/keda.sh_clustertriggerauthentications.yaml
- bases/eventing.keda.sh_cloudeventsources.yaml
# +kubebuilder:scaffold:crdkustomizeresource

## ScaledJob CRD needs to be patched because for some usecases (details in the patch file)


# [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix.
# patches here are for enabling the conversion webhook for each CRD
#- patches/webhook_in_scaledobjects.yaml
#- patches/webhook_in_scaledjobs.yaml
# +kubebuilder:scaffold:crdkustomizewebhookpatch

# [CERTMANAGER] To enable webhook, uncomment all the sections with [CERTMANAGER] prefix.
# patches here are for enabling the CA injection for each CRD
#- patches/cainjection_in_scaledobjects.yaml
#- patches/cainjection_in_scaledjobs.yaml
# +kubebuilder:scaffold:crdkustomizecainjectionpatch

# the following config is for teaching kustomize how to do kustomization for CRDs.
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patches:
- path: patches/scaledjob_patch.yaml
  target:
    group: apiextensions.k8s.io
    kind: CustomResourceDefinition
    name: scaledjobs.keda.sh
    version: v1
- path: patches/scaledobject_patch.yaml
  target:
    group: apiextensions.k8s.io
    kind: CustomResourceDefinition
    name: scaledobjects.keda.sh
    version: v1
