name: FOSSA

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  fossa-key: 9e722f2c8904586d61f97f0bf05a99e4 # This is a public key only for pushing, it's safe here

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: equinix-4cpu-16gb
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4
      - uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5
        with:
          go-version: "1.22"
      - run: go version
      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v8
      - uses: fossas/fossa-action@main
        name: Scanning with FOSSA
        with:
          api-key: ${{ env.fossa-key }}
          branch: ${{ steps.branch-name.outputs.current_branch }}
      - uses: fossas/fossa-action@main
        name: Executing tests with FOSSA
        with:
          api-key: ${{ env.fossa-key }}
          run-tests: true
