name: E2E Test Checker
on:
  pull_request_target:
    types:
      - labeled
      - unlabeled

env:
  SKIP_E2E_TAG: skip-e2e
  E2E_CHECK_NAME: e2e tests

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  e2e-checker:
    name: label checker
    runs-on: ubuntu-latest
    steps:
      - uses: LouisBrunner/checks-action@6b626ffbad7cc56fd58627f774b9067e6118af23 # v2
        name: Enqueue e2e
        id: create
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          sha: ${{ github.event.pull_request.head.sha }}
          name: ${{ env.E2E_CHECK_NAME }}
          status: queued

      - uses: LouisBrunner/checks-action@6b626ffbad7cc56fd58627f774b9067e6118af23 # v2
        name: Skip e2e
        if:  ${{ contains(github.event.pull_request.labels.*.name, env.SKIP_E2E_TAG )}}
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          sha: ${{ github.event.pull_request.head.sha }}
          check_id: ${{ steps.create.outputs.check_id }}
          conclusion: success
          output: |
            {"summary": "skipped by maintainer"}
