name: Reusable workflow to run smoke tests on ARM64

on:
  workflow_call:

jobs:
  smoke-tests-ARM64:
    name: ARM64
    uses: kedacore/keda/.github/workflows/rw-smoke-tests.yml@main
    with:
      runs-on: ARM64
      kubernetesVersion: v1.24
      kindImage: kindest/node:v1.24.0@sha256:406fd86d48eaf4c04c7280cd1d2ca1d61e7d0d61ddef0125cb097bc7b82ed6a1
