name: Reusable workflow to run smoke tests on different k8s versions

on:
  workflow_call:

jobs:
  smoke-tests:
    name: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        kubernetesVersion: [v1.24, v1.23, v1.22, v1.21, v1.20]
        include:
        - kubernetesVersion: v1.24
          kindImage: kindest/node:v1.24.0@sha256:406fd86d48eaf4c04c7280cd1d2ca1d61e7d0d61ddef0125cb097bc7b82ed6a1
        - kubernetesVersion: v1.23
          kindImage: kindest/node:v1.23.6@sha256:1af0f1bee4c3c0fe9b07de5e5d3fafeb2eec7b4e1b268ae89fcab96ec67e8355
        - kubernetesVersion: v1.22
          kindImage: kindest/node:v1.22.9@sha256:6e57a6b0c493c7d7183a1151acff0bfa44bf37eb668826bf00da5637c55b6d5e
        - kubernetesVersion: v1.21
          kindImage: kindest/node:v1.21.12@sha256:ae05d44cc636ee961068399ea5123ae421790f472c309900c151a44ee35c3e3e
        - kubernetesVersion: v1.20
          kindImage: kindest/node:v1.20.15@sha256:a6ce604504db064c5e25921c6c0fffea64507109a1f2a512b1b562ac37d652f3

    uses: kedacore/keda/.github/workflows/rw-smoke-tests.yml@main
    with:
      runs-on: ubuntu-latest
      kubernetesVersion: ${{ matrix.kubernetesVersion }}
      kindImage: ${{ matrix.kindImage }}
