name: "Semgrep"

on:
  push:
    branches: ["main"]
  pull_request_target: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read
  security-events: write

jobs:
  semgrep:
    name: Analyze Semgrep
    runs-on: ubuntu-latest
    container: returntocorp/semgrep
    if: (github.actor != 'dependabot[bot]')
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - name: Register workspace path
        if: ${{ github.event.number > 0 }}
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Checkout Pull Request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        id: checkout
        if: ${{ github.event.number > 0 }}
        run: |
          apk add github-cli
          gh pr checkout ${{ github.event.number }}

      - run: semgrep ci --exclude=test --exclude=test --sarif --output=semgrep.sarif
        env:
          SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}

      - name: Upload SARIF file for GitHub Advanced Security Dashboard
        uses: github/codeql-action/upload-sarif@fe4161a26a8629af62121b670040955b330f9af2 # v3.29.5
        with:
          sarif_file: semgrep.sarif
        if: ${{ github.event.number == '' && !cancelled() }}
