name: Reusable workflow to run smoke tests on s390x

on:
  workflow_call:

jobs:
  smoke-tests-s390x:
    name: Validate k8s
    runs-on: s390x
    steps:
      - name: Setup Go
        uses: actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c # v5
        with:
          go-version: "1.25"

      - name: Install prerequisites
        run: |
          apt update
          apt install curl make ca-certificates gcc libc-dev wget -y
        env:
          DEBIAN_FRONTEND: noninteractive

      - name: Check out code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          fetch-depth: 1

      - name: Install Kubernetes
        run: |
          go install sigs.k8s.io/kind@v0.29.0
          kind create cluster --name ${{ runner.name }} --image vishnubijukumar/kindest-node-s390x:v0.29.0
          kubectl -n kube-system set image daemonset/kindnet kindnet-cni=docker.io/vishnubijukumar/kindnetd:v20250512-s390x
          kubectl -n local-path-storage set image deployment/local-path-provisioner local-path-provisioner=docker.io/vishnubijukumar/local-path-provisioner:v1

          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/s390x/kubectl"
          chmod +x kubectl
          mkdir -p ~/.local/bin
          mv ./kubectl ~/.local/bin/kubectl
          kubectl version

      - name: Run smoke test
        run: make smoke-test

      - name: Upload test logs
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        if: ${{ always() }}
        with:
          name: smoke-test-logs ${{ inputs.runs-on }}-${{ inputs.kubernetesVersion }}
          path: "${{ github.workspace }}/**/*.log"
          if-no-files-found: ignore

      - name: Remove Kubernetes
        run: |
          kind delete cluster --name ${{ runner.name }}
        if: ${{ always() }}
        env:
          DEBIAN_FRONTEND: noninteractive
