name: Reusable workflow to run smoke tests

on:
  workflow_call:
    inputs:
      runs-on:
        required: true
        type: string
      kubernetesVersion:
        required: true
        type: string
      kindImage:
        required: true
        type: string
jobs:
  smoke-tests:
    name: Validate k8s-${{ inputs.kubernetesVersion }}
    runs-on: ${{ inputs.runs-on }}
    steps:
      - name: Setup Go
        uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5
        with:
          go-version: "1.22"

      - name: Install prerequisites
        run: |
          sudo apt update
          sudo apt install curl make ca-certificates gcc libc-dev wget -y
        env:
          DEBIAN_FRONTEND: noninteractive

      - name: Check out code
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4
        with:
          fetch-depth: 1

      - name: Create k8s ${{ inputs.kubernetesVersion }} Kind Cluster
        uses: helm/kind-action@v1.10.0
        with:
          node_image: ${{ inputs.kindImage }}
          cluster_name: smoke-tests-cluster-${{ inputs.kubernetesVersion }}

      - name: Run smoke test
        run: make smoke-test

      - name: Upload test logs
        uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 # v4
        if: ${{ always() }}
        with:
          name: smoke-test-logs ${{ inputs.runs-on }}-${{ inputs.kubernetesVersion }}
          path: "${{ github.workspace }}/**/*.log"
          if-no-files-found: ignore
