name: Reusable workflow to run trivy scan

on:
  workflow_call:
    inputs:
      runs-on:
        required: true
        type: string
      scan-type:
        required: true
        type: string
      format:
        required: true
        type: string
      output:
        required: false
        type: string
        default: trivy.sarif
      image-ref:
        required: false
        type: string
        default: ""
      severity:
        required: false
        type: string
        default: "CRITICAL,HIGH"
      exit-code:
        required: true
        type: number
      publish:
        required: true
        type: boolean

jobs:
  trivy-scan:
    name: Trivy - ${{ inputs.runs-on }} - ${{ inputs.scan-type }} ${{ inputs.image-ref }}
    runs-on: ${{ inputs.runs-on }}
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - name: Run Trivy
        uses: aquasecurity/trivy-action@dc5a429b52fcf669ce959baa2c2dd26090d2a6c4 # v0.32.0
        env:
          TRIVY_DB_REPOSITORY: ghcr.io/kedacore/trivy-db
        with:
          scan-type: ${{ inputs.scan-type }}
          image-ref: ${{ inputs.image-ref }}
          ignore-unfixed: false
          format: ${{ inputs.format }}
          output: ${{ inputs.output }}
          exit-code: ${{ inputs.exit-code }}
          severity: ${{ inputs.severity }}
          trivy-config: trivy.yml

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@51f77329afa6477de8c49fc9c7046c15b9a4e79d # v3.29.5
        if: ${{ inputs.publish }}
        with:
          sarif_file: ${{ inputs.output }}
