name: Reusable workflow to run smoke tests

on:
  workflow_call:
    inputs:
      runs-on:
        required: true
        type: string
      kubernetesVersion:
        required: true
        type: string
      kindImage:
        required: true
        type: string
jobs:
  smoke-tests:
    name: Validate k8s-${{ inputs.kubernetesVersion }}
    runs-on: ${{ inputs.runs-on }}
    steps:
      - name: Setup Go
        uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4
        with:
          go-version: "1.20"

      - name: Install prerequisites
        run: |
          sudo apt update
          sudo apt install curl make ca-certificates gcc libc-dev -y
        env:
          DEBIAN_FRONTEND: noninteractive

      - name: Check out code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
        with:
          fetch-depth: 1

      - name: Create k8s ${{ inputs.kubernetesVersion }} Kind Cluster
        uses: helm/kind-action@v1.8.0
        with:
          node_image: ${{ inputs.kindImage }}
          cluster_name: smoke-tests-cluster-${{ inputs.kubernetesVersion }}

      - name: Run smoke test
        run: make smoke-test

      - name: Upload test logs
        uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32 # v3
        if: ${{ always() }}
        with:
          name: smoke-test-logs ${{ inputs.runs-on }}-${{ inputs.kubernetesVersion }}
          path: "${{ github.workspace }}/tests/**/*.log"
          if-no-files-found: ignore
